color:
  brandColors:
    - '#00585F'
    - '#009393'
    - '#FFFCC4'
    - '#F0EDBB'
    - '#FF3800'
  brandStrength: 0.42535302485339344
  lightness: 0.07220893423072994
  saturation: 0.9657762199640274
  rhythmicContrast: 0.9347495655529201
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: kboyko
layout_spectrum: 0.07664010510779917
typography_spectrum: 0.7801756702829152
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FwN8_eb3l0mw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DwN8_eb3l0mw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FwN8_eb3l0mw%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Thorarinn Jonsson
          url: 'https://www.youtube.com/user/toti1076'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: www.youtube.com
      keywords: []
      description: >-
        www.thor-photography.com Drone and time lapse footage I've shot while
        travelling and guiding photographers in the magnificent landscape of
        Iceland.
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/embed/wN8_eb3l0mw'
      title: The magnificent landscape of Iceland
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/365cf893-0d7e-4588-9fc7-dde13d29fa9a.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8cb7e1bf-5f61-471f-ba22-96a4cd301552.png
content_rating:
  adult: false
author:
  name: Kate
  email: kboyko1999@gmail.com
title: eltit etis yM
description: Place for Katya to have fun
purpose:
  - type: contact
    url: 'mailto:kboyko1999@gmail.com'
    label: Contact me
